import { FC } from "react";
import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/components/layout/Layout'
import LatestStoties, { ILatestStoties } from '@/components/LatestStoties'
import { ICardData, ICardDataMedium } from "@/interfaces/card.interfaces";
import SmallCard from "@/components/cards/SmallCardItem";
import CardItemSmall from "@/components/cards/SmallCardItem";
import { CardData } from "@/pages";
import Movies from "@/components/Movies";
import Travel from "@/components/Travel";
import Pictures from "@/components/Pictures";
import Mission from "@/components/Mission";
import SingUp from "@/components/SingUp";

const inter = Inter({ subsets: ['latin'] })

// export default function Home(cards) {
//   return <>
//   //         <Head>
//   //             <title>App 13.2.4</title>
//   //             <meta name="description" content="Generated by create next app" />
//   //             <meta name="viewport" content="width=device-width, initial-scale=1" />
//   //             <link rel="icon" href="/favicon.ico" />
//   //         </Head>
//   //         <Layout>
//   //             <main >
//   //                 <LatestStoties cards={cards} cardsMedium={cardsMedium}  />
//   //             </main>
//   //         </Layout>
//   //     </>
// }



const Home: FC<CardData> = (props:CardData) => {
    return <>
        <Head>
            <title>App 13.2.4</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
            <main className=" max-h-max">
                <LatestStoties cards={props.cards}  cardsMedium={props.cardsMedium} cardsLarge={props.cards}/>
                <Movies />
                <Travel cards={props.cards}  cardsMedium={props.cardsMedium} cardsLarge={props.cards}/>
                <Pictures />
                <Mission />
                <SingUp />
            </main>
        </Layout>
    </>
}

export default Home